.dev/Manifest.toml, Project.toml, docs/Manifest.toml
Change julia compat entry from 1.9 to 1.8. This will allow us to use ClimaUtilities from ClimaCoupler, which is still running julia 1.8 in CI. Soon, we will update the coupler to use 1.9, and then we can change the compat back to 1.9 here.
----
=> julia compat 1.8, bump patch version

Project.toml, docs/Manifest.toml, docs/make.jl, docs/src/timemanager.md, src/ClimaUtilities.jl, src/TimeManager.jl, test/Project.toml, test/runtests.jl, test/timemanager.jl
Closes #6
- `current_date` function removed, should be added to ClimaCoupler.jl Utilities module
- `trigger_callback` interface has changed, now increments cutoff date internally (so the result must get saved wherever the function is called from), and takes in callback function to be called if condition is met
https://github.com/CliMA/ClimaCoupler.jl/issues/423
- no changes :)
----
=> Add TimeManager module

Project.toml, docs/Manifest.toml, docs/src/datahandling.md, docs/src/regridders.md, src/TimeManager.jl
closes https://github.com/CliMA/ClimaUtilities.jl/issues/20
CFTime is still a dependency in test/Project.toml so that we can test the behavior of `reinterpret`
----
=> remove CFTime direct dependency

docs/src/datahandling.md, docs/src/regridders.md, ext/DataHandlingExt.jl, ext/SpaceVaryingInputsExt.jl, ext/TimeVaryingInputsExt.jl, src/Regridders.jl, test/regridders.jl
closes #23 
- Add function `get_regridder_type` to Regridders.jl. This will check which package extensions are loaded and select a regridder to use based on that. By default, interpolation will be used
- Use `get_regridder_type` in DataHandlingExt if regridder type is not supplied by user
- Add tests
- Note: Tests for 3/4 cases are implemented. I don't think there's a way to clear packages/extensions that are loaded, which we would need to do to check each of the cases of different regridders being available.
----
=> add default regridder_type

.github/workflows/ci.yml, src/OutputPathGenerator.jl, test/clima_artifacts.jl, test/output_path_generator.jl
This PR adds a wait time for certain operations. This is relavent on distributed filesystems, where it can take a little bit of time to propagate that a folder was created/destroyed.
It also adds a test for Julia 1.11.
Closes #38
=> Fix MPI and distributed filesystem (for real this time)

test/clima_artifacts.jl
https://buildkite.com/clima/climautilities-ci/builds/127#018efc0a-213e-406b-a629-e676dd2657d1
The issue is that some MPI processes could run `rm` on a filesystem without the socrates file. By forcing it, all the MPI processes will be able to run `rm` without complaining if no file is there.
=> Fix MPI test 

.buildkite/pipeline.yml
This works by changing the init step in buildkite to:
```yml
steps:
- command: "buildkite-agent pipeline upload"
label: ":pipeline:"
if: "! build.pull_request.labels includes \"Run on clima\""
agents:
queue: new-central
- command: "buildkite-agent pipeline upload"
label: ":pipeline:"
if: "build.pull_request.labels includes \"Run on clima\""
agents:
queue: clima
```
=> Support clima and new-central at the same time

.buildkite/pipeline.yml, NEWS.md, Project.toml, ext/CUDAUtilsExt.jl, ext/TimeVaryingInputs0DExt.jl, test/TestTools.jl, test/clima_artifacts.jl, test/data_handling.jl, test/output_path_generator.jl, test/regridders.jl, test/space_varying_inputs.jl, test/time_varying_inputs.jl
Prior to this commit, the macro CUDA.@cuda was still being parsed, leading to failures when CUDA was not available. I tried adding another `@static` to protect this evaluation, but found that it doesn't work because `Base.get_extension(ClimaComms, :ClimaCommsCUDAExt`) is `nothing`. The reason for this is, I think, `@static` runs at the macro-expansion phase, so when the conditional for `@static` is evaluated, `CUDA` has not been imported yet because `CUDA` is imported with another macro (`ClimaComms.@import_required_backends`). 
The solution I came up with is to put CUDA in an extension for `ClimaUtilities`. This works, but it is a little bit dissatisfying for two reasons. Given that extensions cannot easily use types across each other, I could not add a dispatch over the correct type. …
=> Fix compatibility with ClimaComms 0.6

src/OutputPathGenerator.jl, test/output_path_generator.jl
This PR explicitely disallows empty `output_path`s in `generate_output_path` for the `ActiveLinkStyle`. Previously, this input was not handled correctly: when `""` was passed, a slash would be added, so that `generate_output_path` tried writing to `/output_0000`, which is read-only. Now, we inform the user that their input is invalid.
Fixes #56
=> Do not allow empty output_path

docs/src/outputpathgenerator.md, src/OutputPathGenerator.jl
Windows does not always allow the creation of symbolic links by unprivileged users. This depends on the version of Windows, but also some of its settings. When the creation of symbolic links is not possible, `OutputPathGenerator` will create NTFS junction points instead. Junction points are similar to symbolic links, with the main difference that they
have to refer to directories and they have to be absolute paths. As a result, on systems that do not allow unprivileged users to create symbolic links, moving the base output folder results in breaking the `output_active` link.
Note, I have no way to test if this code is valid besides relying on the CI runners. Additional validation would be helpful.
As a reference, here is the docstring for `symlink`:
```julia …
```
=> Use NTFS junction points when symlinks cannot be created on Windows

docs/src/climaartifacts.md, src/ClimaArtifacts.jl
Julia handles keyword arguments passed with ; in a special way. According to goerz, keyword arguments passed with ; are moved to the front of the macro call. So, we have to handle this case separately
https://discourse.julialang.org/t/documentation-for-how-macros-handle-keyword-arguments/88009
We have to support three cases:
1. context is a ClimaComms.context
2. context is an expression that sets :context = value
3. name (!) is an expression that contains parameters that set the context
The easiest way to go about learning about this is writing a simple macro
macro mymacrotest(first, second)
println("First value: ", first)
println("First type: ", typeof(first))
println("Second value: ", second)
println("Second type: ", typeof(second))
end
Then, test this with the four inputs …
=> Add warning about climaartifacts

NEWS.md, Project.toml, docs/src/outputpathgenerator.md, src/OutputPathGenerator.jl, test/output_path_generator.jl
Soft links are not like hard links or folders. Sometimes, they are treated differently by the operating system (and Julia). As a result, for some operations, an extra step is required to work with the output produced by the ActiveStyle in OutputPathGenerator.
This PR changes the returned path to be the newly created folder instead of the link. The link is still being created and managed, which means that users can still assume that their output can always be found in `output_active`, but the path that is presented to Julia code that uses `OutputPathGenerator` is now the path of the newly created folder. This has the advantage that the path is a normal folder, possibly simplifying certain operations.
=> Change ActiveLinkStyle to return the folder instead of link

.github/workflows/downstream.yml
=> Add downstream tests

NEWS.md, Project.toml, README.md, docs/make.jl, ext/ClimaUtilitiesClimaCommsCUDAExt.jl, ext/ClimaUtilitiesClimaCommsExt.jl, ext/ClimaUtilitiesClimaCoreExt.jl, ext/ClimaUtilitiesClimaCoreInterpolationsExt.jl, ext/ClimaUtilitiesClimaCoreNCDatasetsExt.jl, ext/ClimaUtilitiesClimaCoreTempestRemapExt.jl, ext/ClimaUtilitiesNCDatasetsExt.jl, src/Regridders.jl, test/file_readers.jl
Extensions are defined to mirror the modules defined in src. However, this leads to circular dependencies, where some extensions trigger the loading of others. This is not properly handled by the precompiling logic in Julia as of Julia 1.9-1.11 (fixed in master, upcoming to Julia 1.12, or maybe it will be backported at some point).
Here, I change the way extensions are organized to match the packages that are needed to load them. In this, I still maintain the abstraction that each module in `src` has its implementation in `ext/XYZExt.jl`.
I also added the prefix `ClimaUtilities` to everything to make sure that it won't clash with anything.
Closes #68
=> Reorder extensions

NEWS.md, Project.toml, docs/src/datahandling.md, ext/DataHandlingExt.jl, ext/TimeVaryingInputsExt.jl, src/DataHandling.jl, test/output_path_generator.jl
Reducing allocations. And expose `regridded_snapshot!`
=> Preallocate regridded spaces

test/clima_artifacts.jl
`Base.Filesystem.rm(expected_path, recursive = true)` can fail when run over multiple MPI processes because different ranks might have different view of the filesystem. A possible solution is to add `force = true` (so that ranks will not complain if the file does not exist). In addition to that, we can also explicitly ask that only root executes the rm command
=> Make artifacts test more MPI-robust

docs/src/datastructures.md, src/DataStructures.jl, test/data_structures.jl
Adds expected Dict methods to LRUCache
Closes #79  -- this will automatically close issue 79 on PR merge
Add haskey, copy, deepcopy, empty, empty!, get, pop!, getindex, setindex!, and delete! methods to LRUCache
----
=> Add Dict methods to LRUCache

src/DataStructures.jl
PR #79 adds most methods required for the LRUCache to behave like a dictionary. Now, we can just make it a subtype of `AbstractDict` so that it can be more integrated with the rest of julia's ecosystem.
=> Make LRUCache an AbstractDict

NEWS.md, Project.toml, docs/make.jl, docs/src/datastructures.md, docs/src/inputs.md, ext/TimeVaryingInputs0DExt.jl, ext/TimeVaryingInputsExt.jl, ext/time_varying_inputs_linearperiodfilling.jl, src/DataStructures.jl, src/TimeVaryingInputs.jl, src/Utils.jl, test/data_structures.jl, test/runtests.jl, test/time_varying_inputs.jl, test/time_varying_inputs_linearperiodfilling.jl, test/utils.jl
This PR adds support for period-filling interpolation. From the docstring:
> Perform a period-filling linear interpolation between the two neighboring points.
> 
> This interpolation is period-filling because it ensures that there is no gap on input data
> larger than the given period.
> 
> This interpolation method is best explained with an example. Let us assume data is defined
> on 03/01/1985, 05/01/1985, 11/02/1985, ... 17/12/1985, 07/01/1995, 11/01/1995, 14/02/1995,
> ..., 19/12/1995. In this case, data is defined every 10 years (date format is DD/MM/YYYY).
> You can think of `LinearPeriodFillingInterpolation` as first filling the years in between by
> performing linear interpolation across years, then performs a second linear interpolation
> for the specific day (in actuality, the …
=> Add LinearPeriodFillingInterpolation

NEWS.md, Project.toml, src/DataStructures.jl
`show` uses `iterate` with a state, which was missing. This commits adds it, restoring `show`.
=> Fix show for `LRUCache`

NEWS.md, Project.toml, ext/DataHandlingExt.jl
This bug was found while working with ozone data. Ozone data is defined at non-clean times, eg 2010-07-17T14:11:30.422, and was leading to failures.
The reason for failures are due to moving between times and dates, with times being represented as floating points.
For Float64, times of order of O(few) years (~ 1e7-1e8 seconds) have errors of O(1-100) nanoseconds. As a result, dates like
2010-07-17T14:11:30.422 can be misresolved to 2010-07-17T14:11:30.421 or 2010-07-17T14:11:30.423 when computed from a time. This results in errors because data that is expected to be found is not found.
As a workaround, this commit truncates processing to Milliseconds (because Milliseconds is the time resolution in DateTime) and adds a round operation to recover that resolution.
It is still possible for …
=> Improve handling of floatin gpoint errors in DataHandling times

NEWS.md, docs/src/datahandling.md, docs/src/faqs.md, docs/src/inputs.md, ext/DataHandlingExt.jl, ext/TimeVaryingInputsExt.jl, test/data_handling.jl, test/time_varying_inputs23.jl, test/time_varying_inputs_linearperiodfilling.jl
`t_start` and `reference_date` were added following an incorrect assumption (that restarts would restart at t = 0). The names were taken from ClimaLand/ClimaCouper, where these variables were used slightly differently (`reference_date` might have been the first date available in a file, and `t_start` allowed to run at at different point in that file).
Passing Land build: https://buildkite.com/clima/climaland-ci/builds/5083
=> Remove t_start, rename reference_date->start_date

NEWS.md, ext/TimeVaryingInputsExt.jl, src/Utils.jl
`Utils.isequispaced` is now more efficient: it fails fast and does not allocate as much. More redundant allocations due to `Utils.isequispaced` were fixed.
=> Reduce allocations due to isequispaced

NEWS.md, docs/src/filereaders.md, ext/DataHandlingExt.jl, ext/NCFileReaderExt.jl, src/FileReaders.jl, test/file_readers.jl
Adds a new function `read!` that reads in data to a preallocated space in the DataHandler, as opposed to allocating at each call as the existing `read` does. This requires the addition of a `preallocated_read_data` cache to the `DataHandler` object. 
It also requires that `read` returns a copy of the data in the case of a cache hit to avoid overwriting data in the cache (this was the cause of the bug in the original implementation).
Note that we expect higher allocations when using `read` due to the added `copy`, but lower allocations using `read!` over `read`. Internally, we now use `read!` now so users should see reduced allocations.
This feature was initially introduced in https://github.com/CliMA/ClimaUtilities.jl/pull/83/, but there was a bug in that implementation so it has been …
=> Add read! function

.github/workflows/ci.yml, NEWS.md, src/ClimaArtifacts.jl
https://github.com/JuliaLang/julia/commit/e95eeddb30737962791f51e637dabdfe38c1a9bc changed some internal types in `_artifact_str`, so that `@clima_artifact` stopped working. This fixes it.
Closes #117
=> Fix clima_artifact for Julia 1.12

NEWS.md, Project.toml, src/OutputPathGenerator.jl
This commit increases sleep time across attempts in checking for synced filesystems. This should give the distributed filesystems more time to sync and reduce the occurrence of the "Path not properly synced" error.
Before, the maximum allowed time was 1 second with attempts every 0.1, now it 6 seconds, with exponential backoff.
=> Expand error message and sleep time in maybe_wait

NEWS.md, README.md, docs/make.jl, docs/src/index.md, docs/src/onlinelogging.md, src/ClimaUtilities.jl, src/OnlineLogging.jl, src/OutputPathGenerator.jl, test/onlinelogging.jl, test/output_path_generator.jl
`OnlineLogging` is a new module (mostly based on ClimaAtmos `WallTimeEstimate`) that contains tools to provide informative messages while a simulation is running.
At the moment, `OnlineLogging` only contains `WallTimeInfo`, to report on timing information.
This new module will allow ClimaLand and ClimaCoupler to add some progress information, and remove some entries from the atmos cache.
=> Add OnlineLogging

NEWS.md, docs/src/datastructures.md, ext/DataHandlingExt.jl
This should reduce the memory footprint for long simulations
=> Reduce default max cache size for DataHandlers

NEWS.md, src/ClimaArtifacts.jl
closes #106 - This PR adds a message to the already existing error message that the artifact may be undownloadable and suggests to manually download the artifact and adds the artifact to Overrides.toml if this is the case. We do *not* check if the artifact is undownloadable.
The error message now look like this even if the artifact is downloadable for whatever reason:
```julia
ERROR: Artifact "era5_monthly_averages_pressure_levels_1979_2024" was not found by looking in the paths:
~/.julia/artifacts/dd7ee9500805f590f8fc4c00bfc373eeb7a01587
~/.julia/juliaup/julia-1.11.2+0.x64.linux.gnu/local/share/julia/artifacts/dd7ee9500805f590f8fc4c00bfc373eeb7a01587
~/.julia/juliaup/julia-1.11.2+0.x64.linux.gnu/share/julia/artifacts/dd7ee9500805f590f8fc4c00bfc373eeb7a01587
Try `using Pkg; …
```
=> Improve error message for undownloadable artifacts

docs/src/datahandling.md, docs/src/faqs.md, docs/src/filereaders.md, docs/src/index.md, docs/src/inputs.md, docs/src/onlinelogging.md, docs/src/regridders.md, src/TimeManager.jl
This commit fixes all warnings in the docs,
except for the warning that the modules' docstrings are not included in the documentation.
The warning for Base.close() is no longer thrown,
but the correct docstrings are not shown in the correct places. This cannot be fixed unless the necessary types are exported from the relevant modules.
Closes #141 
----
=> Clean up docs

docs/src/datahandling.md, ext/DataHandlingExt.jl, ext/TimeVaryingInputsExt.jl, ext/time_varying_inputs_linearperiodfilling.jl, src/DataHandling.jl, test/data_handling.jl, test/time_varying_inputs23.jl, test/utils.jl
closes #146 - This commit changes the internal behavior of TimeVaryingInputs23D to use dates rather than seconds since start date. This will make the transition to ITime a little easier since it is easy to convert a ITime to a date.
The behavior of TimeVaryingInputs23D will only differ when `dt` in milliseconds is an odd number or precision more than one millisecond is required. For the first case, this is because the code computes `dt / 2` in `_time_range_dt_dt_e`. In all other cases, the behavior should be identical as before.
=> Changes the internal behavior of TimeVaryingInputs23D to use dates rather than seconds since start date

Project.toml, ext/TimeVaryingInputsExt.jl
`TimeVaryingInputs.TimeVaryingInput` was restricting the arguments that could be passed down to `DataHandler`. In particular, it was not possible to pass vectors of vectors, even if that's something that the `DataHandler` supports.
=> Remove specialization from TVI

ext/InterpolationsRegridderExt.jl, src/Regridders.jl, test/regridders.jl
regrid! stores the regridded data in a pre
allocated ClimaCore field. It also uses
interpolate! instead of interpolate. This still
allocates, but much less. It also may
modify the data passed in, but it does not
seem like that happens when using gridded
interpolation. The function also
requires that the base element type of
the passed in dimensions, undertype of the target space, and eltype of the output field all be the same
Closes #156 
```
infil> @benchmark Regridders.regrid($reg_horz, $data_lon2D, $dimensions2D)
BenchmarkTools.Trial: 10000 samples with 1 evaluation per sample.
Range (min … max):  104.167 μs …  10.438 ms  ┊ GC (min … max): 0.00% … 98.75%
Time  (median):     122.667 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   135.574 μs ± 248.607 μs  ┊ GC (mean ± σ): …
```
=> Add regrid! to InterpolationsRegridder

ext/DataHandlingExt.jl, ext/NCFileReaderExt.jl, ext/nc_common.jl, test/file_readers.jl, test/time_varying_inputs_linearperiodfilling.jl
This PR adds `deferopen = false` when constructing a multifile dataset. According to this issue (https://github.com/JuliaGeo/NCDatasets.jl/issues/277), files are not kept open because of the limitation of 1024 open files on Linux. However, for our use case, this will not matter. 
See this [buildkite](https://buildkite.com/clima/climaland-long-runs/builds/3971#0196b1a7-1aae-4a0c-9df4-6ce556fdc33b) for a ClimaLand run for a single year with ~40 years of ERA5 forcing data without this change.
See this [buildkite](https://buildkite.com/clima/climaland-long-runs/builds/3987#0196cad7-4762-452d-b592-899dc75cc2f0) for a ClimaLand run for a single year with ~40 years of ERa5 forcing data with this change.
Also, see this [buildkite](https://buildkite.com/clima/climaland-long-runs/builds/3977#0196b25 …
=> Add deferopen = false when constructing multifile dataset

NEWS.md, docs/src/regridders.md, ext/InterpolationsRegridderExt.jl, test/regridders.jl
This PR exposes the interpolation method to the users, so that they can change from `Intp.Linear()` to `Intp.Constant()` for example.
TODO
=> Expose interpolation method to users

ext/TimeVaryingInputs0DExt.jl, src/ITime.jl, test/itime.jl, test/time_varying_inputs.jl
Add tests for TimeVaryingInput0D for 0D TVI
with times of floats, ITime with no epoch, and ITime with epoch.
Tests 0d TVI of floats can evaluate at ITime inputs, floating point inputs, and tests that an error is thrown with a datetime input.
Test that error is thrown when evaluating a TVI of ITimes with no epoch at a DateTime.
Test that TVI of ITime with epoch can be evaluated at ITimes, floats, or DateTimes.
Test that TVI of ITime with no epoch can be evaluated at ITimes or floats.
Make all the above tests pass by adding conversions to the `evaluate!` methods.
Add `Float64(::ITime)` and `Float32(::Time)`
Tried changing ITime and floating point  multiplication behavior to attempt to use a smaller period if the result of the multiplication is less than 1, but that is a behavior change, so …
=> ITime housekeeping

NEWS.md, Project.toml, ext/InterpolationsRegridderExt.jl, test/regridders.jl
Previously, this would error because the interpolator would be constructed with dimensions corresponding to the 2D input data, but then try to regrid onto the 3D coordinates. The solution in this PR is to handle that case by displaying a warning and dropping the z dimension while interpolating.
Closes #174
----
=> Allow regridding 2D data onto 2D spaces with LatLongZ coordinates

.github/workflows/ci.yml, Project.toml, ext/InterpolationsRegridderExt.jl, test/regridders.jl
In ClimaLand this warning comes up mulitiple times per simulation and clogs the output log.
As of this recent PR https://github.com/JuliaLang/julia/pull/59238, StaticData no longer exists in the nightly Julia version. This module is accessed somewhere in ClimaTimeSteppers/StaticArrayInterface/FastBroadcast/DiffEqBase. We shouldn't rely on upstream packages being compatible with the main branch of Julialang anyway, so I'm removing the nightly Julia tests.
=> remove LatLongZ regridding warning; remove Julia nightly test; tag patch release

ext/TimeVaryingInputs0DExt.jl, test/time_varying_inputs.jl
Promoting a large number of ITimes is expensive, so this modifies the behavior to only do so if needed.
Closes #186
----
=> Change TVI0d constructor to conditionally promote
