.dev/Manifest.toml, .dev/Project.toml, .dev/clima_formatter_options.jl, .dev/climaformat.jl, .dev/hooks/pre-commit, .github/codecov.yml, .github/workflows/CodeCov.yml, .github/workflows/CompatHelper.yml, .github/workflows/JuliaFormatter.yml, .github/workflows/TagBot.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, .gitignore, NOTICE, Project.toml, README.md, docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/index.md, src/ClimaUtilities.jl, test/Project.toml, test/aqua.jl, test/runtests.jl
Generic setup for the new repo, including folder structure and Project.toml files.
Closes #2
----
=> set up repo

.dev/Manifest.toml, docs/Manifest.toml
use newest version of julia
closes #16
----
=> use julia 1.9.3

.buildkite/pipeline.yml, ext/DataHandlingExt.jl, ext/TempestRegridderExt.jl, src/ClimaArtifacts.jl, src/OutputPathGenerator.jl, test/TestTools.jl, test/clima_artifacts.jl, test/data_handling.jl, test/output_path_generator.jl, test/regridders.jl, test/space_varying_inputs.jl, test/time_varying_inputs.jl
The MPI pipeline was not being run with MPI
=> Fix MPI test

.buildkite/pipeline.yml, NEWS.md, docs/src/datahandling.md, docs/src/datastructures.md, docs/src/filereaders.md, docs/src/index.md, ext/DataHandlingExt.jl, ext/NCFileReaderExt.jl, src/ClimaUtilities.jl, src/DataHandling.jl, src/DataStructures.jl, test/data_structures.jl, test/runtests.jl
=> add LRU cache

NEWS.md, Project.toml, docs/Manifest.toml
To be merged after #33, so downstream packages can use these fixes
=> bump patch version

.buildkite/pipeline.yml, NEWS.md, docs/src/datahandling.md, docs/src/inputs.md, docs/src/regridders.md, ext/DataHandlingExt.jl, ext/SpaceVaryingInputsExt.jl, ext/TempestRegridderExt.jl, ext/TimeVaryingInputsExt.jl, test/data_handling.jl
This PR exposes some constructor options to the higher level abstractions.
Closes #22 
cc: @kmdeck
=> Add support for passing arguments down to the regridder and file reader

docs/src/regridders.md, ext/DataHandlingExt.jl, ext/TempestRegridderExt.jl, test/data_handling.jl
closes https://github.com/CliMA/ClimaUtilities.jl/issues/65
related https://github.com/CliMA/ClimaCoupler.jl/issues/764
Tested in ClimaCoupler in singleton CPU, MPI, and GPU cases: https://buildkite.com/clima/climacoupler-ci/builds/4019#0190282c-6ea6-4f74-a964-70ea9749a3b4
Tested in ClimaLand: https://buildkite.com/clima/climaland-ci/builds/4314
----
=> conditionally use spacefillingcurve

test/TestTools.jl, test/time_varying_inputs.jl
This PR adds a test for `InterpolationRegridder` that checks that we can work on lat-long boxes.
=> Test remapping with regional domains

test/runtests.jl
Fix method definition overwritten warnings in tests
Closes #93  -- this will automatically close issue 2 on PR merge
----
=> Fix warnings in tests

README.md
=> Add Readme badges

src/TimeVaryingInputs.jl
=> Update doc string for `LinearPeriodFillingInterpolation`

docs/make.jl, docs/src/faqs.md, docs/src/inputs.md
This commit adds a new Frequently Asked Questions page and provides more documentation on how to change units in `Input`s.
=> Add FAQs and more documentation

NEWS.md, Project.toml
=> update news and project toml version

docs/src/inputs.md
=> Fix arg in doc function. 

.github/workflows/downstream.yml
Following https://github.com/CliMA/ClimaCoupler.jl/pull/1033
=> Update downstream job for Julia 1.11 and AMIP

docs/make.jl, docs/src/climaartifacts.md, docs/src/datastructures.md, docs/src/filereaders.md, docs/src/index.md, docs/src/inputs.md, docs/src/regridders.md, src/TimeVaryingInputs.jl, src/Utils.jl
The correct notation is
```
!!! note
```
Not what I had before
Closes #129
=> Fix notes in docs

docs/src/climaartifacts.md, docs/src/index.md, docs/src/regridders.md
!!!note does not create an admonition. This is an extension to PR #134 
----
=> Change !!!note to !!! note

NEWS.md, Project.toml, docs/src/datahandling.md, docs/src/inputs.md, ext/DataHandlingExt.jl, test/data_handling.jl
This commit surfaces the new capability introduced recently in NCFileReaders to read multiple files as if they were one.
Closes #126
=> Expose support for multiple files to DataHandler

docs/src/inputs.md
=> Docs: add example of changing boundary conditions

src/ITime.jl, test/itime.jl
This PR makes `float` and `date` not overflow.
=> Make float and date of ITime not overflow

src/ITime.jl, test/itime.jl
This should be integer division and division which promote the result to a float.
=> Should be integer division and not a float

test/regridders.jl
The InterpolationsRegridder tests have been checking that the maximum difference between regridded and reference values is below a threshold, but without taking the absolute value of the difference. This led tests to pass when they should have failed.
Closes #175
=> fix tests for longitude regridding

ext/NCFileReaderExt.jl
This makes it easier to use ERA nc files without preprocessing
----
=> Add valid_time to the possible time dim names in NCFileReader
